# Site settings
title: A blog about Chiho
description: A blog about Chiho
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "http://www.travelflan.com/"

# User settings
username: Chiho Yoon
user_description: Junior Frontend Engineer, specialised in VueJS and ECMAScript 2015. Former GIS engineer. Currently playing a major role at a Hong Kong based AI startup as a great team player & communicator.
user_title: Frontend Engineer, Web Developer, GIS Specialist
email: chiho1jjan@naver.com
github_username: chonim

# Google-analytics
google-analytics:
  id: "UA-96178108-1"

exclude: ['package.json', 'src' , 'node_modules']

# jekyll s
# browser-sync start --proxy "localhost:4000" --files "_site/**/*"
